import platform
import sys
from datetime import date
import random



#Varibles
a = 0
b = 1
random = random.randint
ver = 'Version: v1.9.5.3 Welcome Penguins'

print('Welcome')
name = input('What is Your Name?')
print('Hello, ' + name)
print('I am OpenArchive, a Free and Opensource Archive')

#DATA HERE

def get_hardware_info():
    system_info = platform.uname()

cpuinfo = platform.uname()

#All of the syntax for OpenArchive are right here!!!
data_lib = {
    'archive_age'         : 'Older Than 1 Days Old',
    'archive_creator'     : 'Logan Kaval',
    'archive_purpose'     : 'To Help People Remember Stuff',
    'archive_hardware'    : cpuinfo,
    'archive_contributors': 'Logan Kaval,',
    'archive_usr'         : name,
    'pla_print_temp'      : '190C to 220C',
    'tpu_print_temp'      : '210C to 230C',
    'water_comp'          : '2 Hydrogen and 1 Oxygen',
    "archive_ver"         : ver,
    'help_syntax'         : ' ',
    'what_nixos'          : 'NixOS is a Linux Operating System that is Normally Easy to Duplicate.',
    'what_arch'           : 'Arch is a Linux Distro With its Own Package Manager Called Pacman',
    'what_debiangnu/linux': 'The Debian Project is an association of individuals who have made common cause to create a free operating system. This operating system is called Debian. Debian systems currently use the Linux kernel. Linux is a completely free piece of software started by Linus Torvalds and supported by thousands of programmers worldwide. Of course, the thing that people want is application software: programs to help them get what they want to do done, from editing documents to running a business to playing games to writing more software. Debian comes with over 50,000 packages (precompiled software that is bundled up in a nice format for easy installation on your machine) - all of it free. Its a bit like a tower. At the base is the kernel. On top of that are all the basic tools. Next is all the software that you run on the computer. At the top of the tower is Debian -- carefully organizing and fitting everything so it all works together.',
    'what_gentoo'         : 'Gentoo is a Linux Distro That is Very Basic. Gentoo is made for Developers and Network Proffessionals. It has its Own Package Manager Called Portage.',
    'what_linux'          : 'Linux is a Operating System (OS) That Can Revive Old Computers, or Can Make YOur Computer Faster. It Can Also Make Your Computer More Stable. Linux Does Have its Downsides too. Linux is Very Different From Windows Because in Windows You Install Stuff With the Browser. Linux Installs Stuff With the Terminal.',
    'what_windows'        : 'Windows is a Proprietary Operating System (OS) That is Widely Used. It Has Lots of Applications Written for it.',
    'what_macos'          : 'MacOS is the Operating System (OS) That Macs Run. It is a Proprietary OS That Mainly Only Runs On Macs, But People Have Found Out Ways to Change That.',
    'what_fedora'         : 'Fedora is a Linux Operating System (OS) That is Pretty New. It was Created by Red Hat.',
    'used_resources'      : 'Some of These Linux Answers are from distrowatch.com!',
    'what_ultramarine'    : 'Ultramarine Linux is a Fedora-based distribution featuring extra package repositories such as RPM Fusion, the Budgie (or Cutefish) desktop, and multimedia codecs. Ultramarine can be considered a spiritual successor to Korora Project and aims to make Fedora a more desktop-friendly experience.',
    'what_peppermintos'   : 'Peppermint OS is a Debian- and Devuan-based (previously a Lubuntu-based) Linux distribution that aims to be fast and easy on system resources. By employing its Site Specific Browser, Peppermint integrates seamlessly with cloud and web-based applications. The distributions other features include straight forward updates and easy step-by-step installation using the Calamares installer. The distribution once employed a hybrid LXDE/Xfce desktop environment, mixing LXDEs lxsession with Xfces panel and application menu. Starting in 2022, Peppermint OS shifted to using the Xfce desktop, dropping the LXDE components.',
    'what_kali'           : 'Kali Linux (formerly known as BackTrack) is a Debian-based distribution with a collection of security and forensics tools. It features timely security updates, support for the ARM architecture, a choice of four popular desktop environments, and seamless upgrades to newer versions.',
    'what_rlxos'          : 'rlxos is an independent Linux distribution which runs on an immutable filesystem and features the Xfce desktop. The project features the Distrobox container manager to facilitate running software from multiple other distributions. It also includes support for Flatpak and includes the Bolt AI assistant.',
    'what_rocky'          : 'Rocky Linux is a community enterprise operating system designed to be 100% bug-for-bug compatible with Red Hat Enterprise Linux. It is available for the x86_64 and AArch64 processor architectures.',
    'what_endeavouros'    : 'EndeavourOS is a rolling release Linux distribution based on Arch Linux. The project aims to be a spiritual successor to Antergos - providing an easy setup and pre-configured desktop environment on an Arch base. EndeavourOS offers both off-line and on-line install options. The off-line installer, Calamares, uses the Xfce desktop by default. The on-line installer can install optional software components, including most popular desktop environments.',
    'what_oracle'         : 'Oracle Linux is an enterprise-class Linux distribution supported by Oracle and built from source packages for Red Hat Enterprise Linux (RHEL). Some of the special features of Oracle Linux include a custom-build and rigorously-tested Linux kernel called Oracle Unbreakable Kernel, tight integration with Oracles hardware and software products including most database applications, and zero downtime patching - a feature that enables administrators to update the kernel without a reboot.',
    'what_pfsense'        : 'pfSense is a free, open source customized distribution of FreeBSD specifically tailored for use as a firewall and router that is entirely managed via web interface. In addition to being a routing platform, pfSense includes a long list of related features and a package system which allows further expandability.',
    'what_eurolinux'      : 'EuroLinux is an enterprise-class Linux distribution made and supported by the EuroLinux company, built mostly from code of Red Hat Enterprise Linux. The origin of the system ensures compatibility with most popular enterprise Linux distributions including Red Hat Enterprise Linux, Oracle Linux, and CentOS. While primarily geared toward server workloads, EuroLinux can also be used for desktop computing or any environment where long-term stability and support are demanded.',
    'what_reactos'        : 'ReactOS is a free and open-source operating system based on the best design principles found in the Windows NT architecture. Written completely from scratch, ReactOS is not a Linux-based system and it shares none of the UNIX architecture. The main goal of the ReactOS project is to provide an operating system which is binary compatible with Windows. This will allow Windows applications and drivers to run as they would on a Windows system. Additionally, the look and feel of the Windows operating system is used, such that people accustomed to the familiar user interface of Windows would find using ReactOS straightforward. The ultimate goal of ReactOS is to allow people to use it as an alternative to Windows without the need to change software they are used to.',
    'what_void'           : 'Void is an independently-developed, general-purpose operating system based on the monolithic Linux kernel. It features a hybrid binary/source package management system which allows users to quickly install, update and remove software, or to build software directly from sources with the help of the XBPS source packages collection. Other features of the distribution include support for Raspberry Pi single-board computers (both armv6 and armv7), rolling-release development model with daily updates, and native init system called "runit".',
    'what_altlinux'       : 'ALT Linux was founded in 2001 by a merge of two large Russian free software projects. By the year 2008 it became a large organization developing and deploying free software, writing documentation and technical literature, supporting users, and developing custom products. ALT Linux produces different types of distributions for various purposes. There are desktop distributions for home and office computers and for corporate servers, universal distributions that include a wide variety of development tools and documentation, certified products, distributions specialized for educational institutions, and distributions for low-powered computers. ALT Linux has its own development infrastructure and repository called Sisyphus, which provides the base for all the different editions of ALT Linux.',
    'what_rhinolinux'     : 'Rhino Linux is an Ubuntu-based distribution which offers a rolling-release upgrade approach. The distribution uses a customised Xfce desktop environment. Rhino features a custom meta package manager which unifies Deb, Pacstall and Flatpak software management.',
    'what_murena'         : 'Murena is an umbrella name for the /e/OS operating system, associated open source powered smartphones, and cloud-based services. The Murena project provides open source images for common smartphones, open source cloud-based storage, calendar, and backup solutions, and sells phones with /e/OS pre-installed. The projects operating system is based on LineageOS, itself based on Android. The Murena team removes closed source applications, trackers, and Google-specific elements of Android and replaces them with open source alternatives.',
    'what_tails'          : 'The Amnesic Incognito Live System (Tails) is a Debian-based live DVD/USB with the goal of providing complete Internet anonymity for the user. The product ships with several Internet applications, including web browser, IRC client, mail client and instant messenger, all pre-configured with security in mind and with all traffic anonymised. To achieve this, Incognito uses the Tor network to make Internet traffic very hard to trace.',
    'what_mxlinux'        : 'MX Linux, a desktop-oriented Linux distribution based on Debians Stable branch, is a cooperative venture between the antiX and former MEPIS Linux communities. Using Xfce as the default desktop (with separate KDE Plasma and Fluxbox editions also available), it is a mid-weight operating system designed to combine an elegant and efficient desktop with simple configuration, high stability, solid performance and medium-sized footprint.',
    'what_linuxmint'      : 'Linux Mint is an Ubuntu-based distribution whose goal is to provide a classic desktop experience with many convenient, custom tools and optional out-of-the-box multimedia support. It also adds a custom desktop and menus, several unique configuration tools, and a web-based package installation interface. Linux Mint is compatible with Ubuntu software repositories. Besides its Ubuntu-based flavour, the project also produces a separate "Debian" edition (called LMDE), based on the latest stable Debian version.',
    'what_ubuntu'         : 'Ubuntu is a complete desktop Linux operating system, freely available with both community and professional support. The Ubuntu community is built on the ideas enshrined in the Ubuntu Manifesto: that software should be available free of charge, that software tools should be usable by people in their local language and despite any disabilities, and that people should have the freedom to customise and alter their software in whatever way they see fit. "Ubuntu" is an ancient African word, meaning "humanity to others". The Ubuntu distribution brings the spirit of Ubuntu to the software world.',
    'what_pop!_os'        : 'Pop!_OS is an Ubuntu-based Linux distribution featuring a custom GNOME desktop. Pop!_OS is designed to have a minimal amount of clutter on the desktop without distractions in order to allow the user to focus on work. The distribution is developed by Linux computer retailer System76.',
    'what_opensuse'       : 'The openSUSE project is a community program sponsored by SUSE Linux and other companies. Promoting the use of Linux everywhere, this program provides free, easy access to openSUSE, a complete Linux distribution. The openSUSE project has three main goals: make openSUSE the easiest Linux for anyone to obtain and the most widely used Linux distribution; leverage open source collaboration to make openSUSE the worlds most usable Linux distribution and desktop environment for new and experienced Linux users; dramatically simplify and open the development and packaging processes to make openSUSE the platform of choice for Linux developers and software vendors.',
    'what_zorinos'        : 'Zorin OS is an Ubuntu-based Linux distribution designed especially for newcomers to Linux. It has a Windows-like graphical user interface and many programs similar to those found in Windows. Zorin OS also comes with an application that lets users run many Windows programs. The distributions ultimate goal is to provide a Linux alternative to Windows and let Windows users enjoy all the features of Linux without complications.',
    'what_garudalinux'    : 'Garuda Linux is a rolling distribution based on the Arch Linux operating system. Unlike Arch Linux, Garuda Linux comes with a graphical installer (Calamares) for easy installation, and other advanced graphical tools for managing your system. Garuda is a performance-oriented distro with many performance enhancing tweaks. Some of the many tweaks include using zram, a performance CPU governor, along with custom memory management software. Garuda Linux has striven to provide system stability by including the Timeshift backup utility.',
    'what_linuxlite'      : 'Linux Lite is a beginner-friendly Linux distribution based on Ubuntus long-term support (LTS) release and featuring the Xfce desktop. Linux Lite primarily targets Windows users. It aims to provide a complete set of applications to assist users with their everyday computing needs, including a full office suite, media players and other essential daily software.',
    'what_antix'          : 'antiX is a fast, lightweight and easy-to-install Linux live CD distribution based on Debians Stable branch for x86 compatible systems. antiX offers users the "antiX Magic" in an environment suitable for old computers. The goal of antiX is to provide a light, but fully functional and flexible free operating system for both newcomers and experienced users of Linux. It should run on most computers, ranging from 256 MB old PIII systems with pre-configured swap to the latest powerful boxes. 256 MB RAM is recommended minimum for antiX. The installer needs minimum 2.7 GB hard disk size. antiX can also be used as a fast-booting rescue CD, or run live on a USB stick, with or without persistent file storage.',
    'what_kde_neon'       : 'KDE neon is a Ubuntu-based Linux distribution and live DVD featuring the latest KDE Plasma desktop and other KDE community software. Besides the installable DVD image, the project provides a rapidly-evolving software repository with all the latest KDE software. Two editions of the product are available - a "User" edition, designed for those interested in checking out the latest KDE software as it gets released, and a "Developers" edition, created as a platform for testing cutting-edge KDE applications.',
    'what_elementaryos'   : 'elementary OS is an Ubuntu-based desktop distribution. Some of its more interesting features include a custom desktop environment called Pantheon and many custom apps including Photos, Music, Videos, Calendar, Terminal, Files, and more. It also comes with some familiar apps like the Epiphany web browser and a fork of Geary mail.',
    'what_nobara_project' : 'Nobara Project is a modified version of Fedora Linux with user-friendly fixes added to it. The distribution comes with certain features that do not ship with the regular Fedora, such as WINE dependencies, OBS Studio, 3rd party codec packages for GStreamer, NVIDIA drivers, and some package fixes. Nobara aims to fix most of those issues and offer a better gaming, streaming and content creation experience out of the box. The projects official release comes with a custom-themed GNOME desktop, but it also offers separate editions with standard GNOME and KDE desktops.',
    'what_mageia'         : 'Mageia is a fork of Mandriva Linux formed in September 2010 by former employees and contributors to the popular French Linux distribution. Unlike Mandriva, which is a commercial entity, the Mageia project is a community project and a non-profit organisation whose goal is to develop a free Linux-based operating system.',
    'what_vanillaos'      : 'Vanilla OS, a fixed-release distribution based on Ubuntu with the GNOME desktop, is an immutable operating system. The core parts of the system are locked down to prevent unwanted changes and corruption from third-party applications or a faulty update.',
    'what_pclinuxos'      : 'PCLinuxOS is a user-friendly Linux distribution with out-of-the-box support for many popular graphics and sound cards, as well as other peripheral devices. The bootable live DVD provides an easy-to-use graphical installer and the distribution sports a wide range of popular applications for the typical desktop user, including browser plugins and full multimedia playback. The intuitive system configuration tools include Synaptic for package management, Addlocale to add support to many languages and Mylivecd to create a customised live CD.',
    'what_sparkylinux'    : 'SparkyLinux is a lightweight, fast and simple Linux distribution designed for both old and new computers featuring customised Enlightenment and LXDE desktops. It has been built on the "testing" branch of Debian GNU/Linux.',
    'what_puppy'          : 'Puppy Linux is yet another Linux distribution. Whats different here is that Puppy is extraordinarily small, yet quite full-featured. Puppy boots into a ramdisk and, unlike live CD distributions that have to keep pulling stuff off the CD, it loads into RAM. This means that all applications start in the blink of an eye and respond to user input instantly. Puppy Linux has the ability to boot off a flash card or any USB memory device, CDROM, Zip disk or LS/120/240 Superdisk, floppy disks, internal hard drive. It can even use a multisession formatted CD-RW/DVD-RW to save everything back to the CD/DVD with no hard drive required at all.',
    'what_almalinuxos'    : 'AlmaLinux OS is an open-source, community-driven project that is built from the source code of Red Hat Enterprise Linux (RHEL). AlmaLinux is a completely binary compatible fork of RHEL and it is maintained by AlmaLinux OS Foundation which is a register non-profit.',
    'what_cachyos'        : 'CachyOS is a Linux distribution based on Arch Linux. It focuses on speed and security optimisations - the default Linux kernel is heavily optimised using the BORE (Burst-Oriented Response Enhancer) scheduler, while the desktop packages are compiled with LTO and x86-64-v3 optimization, security flags and performance improvements. The available desktop environments and window managers include KDE Plasma, GNOME, Xfce, i3, bspwm, LXQt, Openbox, Wayfire and Cutefish. CachyOS also ships with both graphical and command-line installers and provides a Firefox-based browser (called Cachy-Browser) with some security enhancements and performance optimisations.',
    'what_arcolinux'      : 'ArcoLinux (previously known as ArchMerge) is a distribution based on Arch Linux. The development takes places in three branches - ArcoLinux, ArcoLinuxD and ArcoLinuxB. ArcoLinux is a full-featured distribution that ships with the Xfce desktop (as well as Openbox and i3 window managers). ArcoLinuxD is a minimal distribution that includes scripts that enable power users to install any desktop and application. ArcoLinuxB is a project that gives users the power to build custom distributions, while also developing several community editions with pre-configured desktops, such as Awesome, bspwm, Budgie, Cinnamon, Deepin, GNOME, MATE and KDE Plasma. ArcoLinux also provides various video tutorials as it places strong focus on learning and acquiring Linux skills.',
    'what_q4os'           : 'Q4OS is a Debian-based desktop Linux distribution designed to offer classic-style user interface (Trinity) and simple accessories, and to serve stable APIs for complex third-party applications, such as Google Chrome, VirtualBox and development tools. The system is also very useful for virtual cloud environments due to its very low hardware requirements.',
    'what_easyos'         : 'EasyOS is an experimental Linux distribution which uses many of the technologies and package formats pioneered by Puppy Linux. The distribution features custom container technology called Easy Containers which can run applications or the entire desktop environment in a container. Packages, desktop settings, networking and sharing resources over the network can all be controlled through graphical utilities.',
    'what_tuxedoos'       : 'TUXEDO OS is an Ubuntu-based distribution developed in Germany by TUXEDO Computers GmbH, designed and optimised for the companys own range of Linux-friendly personal computers and notebooks. The distribution uses KDE Plasma as the preferred desktop. Some of the differences between Ubuntu and TUXEDO OS include custom boot menu, the TUXEDO Control Centre, Calamares installer, availability of the Lutris open gaming platform, preference for the PipeWire audio daemon (over PulseAudio), removal of Ubuntus snap daemon and snap packages, and various other tweaks and enhancements.',
    'what_devuangnu+linux': 'Devuan GNU+Linux is a Linux distribution forked from Debian in 2015. The projects primary goal is to provide a variant of Debian without the complexities and dependencies of systemd, an init system and services manager originally developed by Red Hat and later adopted by most other Linux distributions. Devuans initial beta release was made available in April 2016, together with an upgrade path from Debian 7.0 "Wheezy" and a possibility to switch to Devuan from Debian 8.0 "Jessie". The distribution adopted Xfce as its default desktop.',
    'what_alpinelinux'    : 'Alpine Linux is a community developed operating system designed for routers, firewalls, VPNs, VoIP boxes, containers, and servers. It was designed with security in mind; it has proactive security features like PaX and SSP that prevent security holes in the software to be exploited. The C library used is musl and the base tools are all in BusyBox. Those are normally found in embedded systems and are smaller than the tools found in GNU/Linux systems.',
    'what_blendos'        : 'blendOS is an Arch Linux-based, rolling release distribution which automates installing software from supported distributions (Arch, Fedora, and Ubuntu) into containers. blendOS tries to make software management in across containers feel native and provides access to the users home directory for each container.',
    'what_solus'          : 'Solus is a Linux distribution built from scratch. It uses a forked version of the PiSi package manager, maintained as "eopkg" within Solus, and a custom desktop environment called "Budgie", developed in-house. The Budgie desktop, which can be set to emulate the look and feel of the GNOME 2 desktop, is tightly integrated with the GNOME stack. The distribution is available for 64-bit computers only.',
    'what_voyagerlive'    : 'Voyager Live is an Xubuntu-based distribution and live DVD showcasing the Xfce desktop environment. Its features include the Avant Window Navigator or AWN (a dock-like navigation bar), Conky (a program which displays useful information on the desktop), and over 300 photographs and animations that can be used as desktop backgrounds. The project also develops several other editions of Voyager Live - a "GE" edition with GNOME Shell, a "GS" variant for Gamers, and a separately-maintained flavour based on Debians stable branch.',
    'what_kubuntu'        : 'Kubuntu is a free, user-friendly Linux distribution based on KDEs desktop software and on the Ubuntu operating system. It has a biannual release cycle. Besides providing an up-to-date version of the KDE desktop at the time of the release, the project also releases updated KDE packages throughout the lifetime of each release.',
    'what_bodihlinux'     : 'Bodhi Linux is an elegant and lightweight Debian/Ubuntu-based distribution featuring Moksha, an Enlightenment-17-based desktop environment. The project takes a decidedly minimalist approach by offering modularity, high levels of customisation, and choice of themes. Bodhi releases come in several editions, including Standard (64-bit) and Legacy (32-bit) which are minimalist, only including a web browser, terminal, file manger, text editor and photo GUI applications, while the AppPack edition includes more applications and tools preinstalled. Additional software can be added with Bodhis web-based AppCenter, Synaptic, and APT.',
    'what_smartos'        : 'SmartOS is an open-source UNIX-like operating system based on illumos, a community fork of OpenSolaris. It features four technologies - ZFS (a combined file system and logical volume manager), DTrace (a dynamic tracing framework for troubleshooting kernel and application problems), Zones (a lightweight virtualisation solution), KVM and bhyve (two full virtualisation solutions for running a variety of guest operating systems, including Linux, Windows, BSD and Plan9). SmartOS is designed to be particularly suitable for building clouds and generating appliances.',
    'what_slackwarelinux' : 'The Official Release of Slackware Linux by Patrick Volkerding is an advanced Linux operating system, designed with the twin goals of ease of use and stability as top priorities. Including the latest popular software while retaining a sense of tradition, providing simplicity and ease of use alongside flexibility and power, Slackware brings the best of all worlds to the table. Originally developed by Linus Torvalds in 1991, the UNIX-like Linux operating system now benefits from the contributions of millions of users and developers around the world. Slackware Linux provides new and experienced users alike with a fully-featured system, equipped to serve in any capacity from desktop workstation to machine-room server. Web, ftp, and email servers are ready to go out of the box, as are a wide selection of popular desktop environments. A full range of development tools, editors, and current libraries is included for users who wish to develop or compile additional software.',
    'what_gnoppixlinux'   : 'Gnoppix is a Debian and Kali Linux-based distribution which can be run from a DVD, USB thumb drive or from a local drive. It can resume previous sessions while running in a live mode. The distribution attempts to clean up after itself, removing all traces of its use from the computer or used media. Prior to version 22, Gnoppix was a Knoppix-based distribution and live medium featuring the GNOME desktop.',
    'what_spirallinux'    : 'SpiralLinux is a selection of desktop spins built from Debian GNU/Linux, with a focus on simplicity and out-of-the-box usability across all the major desktop environments. SpiralLinux serves as an alternative live installation method for a highly reliable customized Debian system using only official Debian package repositories. Unlike Debians official install media, SpiralLinux includes non-free firmware. It also provides popular media codecs out of the box.',
    'what_xerolinux'      : 'XeroLinux is an Arch Linux-based distribution with KDE Plasma as the preferred desktop. Some of the features of the distribution include the Calamares installer, various under-the-hood tweaks and optimisations, built-in support for community-built AUR packages as well as Flatpak packages, and the availability of various desktop and bootloader themes developed in-house.',
    'what_regataos'       : 'Regata OS is a Brazilian Linux distribution based on openSUSE, focusing on desktop and gaming needs. Its main characteristics include a Regata OS store for installing applications and games, out-of-the-box integration with Google Drive, support for a gaming mode via the Vulkan graphics API, an extensive library of games in the Regata OS Game Access portal, support for configuration of hybrid graphics in notebooks, and easy transfer of files between a computer and a smartphone. The distributions user interface is KDE Plasma.',
    'what_kaos'           : 'KaOS is a desktop Linux distribution that features the latest version of the KDE desktop environment, the Calligra office suite, and other popular software applications that use the Qt toolkit. It was inspired by Arch Linux, but the developers build their own packages which are available from in-house repositories. KaOS employs a rolling-release development model and is built exclusively for 64-bit computer systems.',
    'what_pureos'         : 'PureOS is a GNU/Linux distribution based on Debian. It is a desktop distribution that can be used as live media (CD or USB) or as full-featured operating systems installed on a hard disk. PureOS uses free and open source software exclusively and is endorsed by the Free Software Foundation. It ships with some privacy features enabled by default such as using DuckDuckGo as the search engine and the HTTPS Everywhere browser extension is enabled.',
    'what_lubuntu'        : 'Lubuntu is a variant of Ubuntu that uses the LXQt desktop environment. (Versions prior to 18.10 shipped with the LXDE desktop.) It includes essential applications and services for daily use, including office suite, PDF reader, image editor and multimedia players. A distribution available for both 32-bit and 64-bit computers, Lubuntu is intended to be user-friendly, lightweight and energy efficient.',
    'what_bluestar'       : 'Bluestar Linux is a GNU/Linux distribution that is based on Arch Linux. The Bluestar distribution features up to date packages, a full range of desktop and multimedia software in the default installation and a live desktop DVD.',
    'what_athenaos'       : 'Athena OS is an Arch-derived Linux distribution designed for penetration testing, bug-bounty hunting and InfoSec students. The distribution provides a way to connect directly to some of the e-learning hacking resources, such as Hack The Box, Offensive Security, PWNX and InfoSec certifications, and it provides integration with the Hack The Box hacking platform and connections to InfoSec communities. Athena OS also introduces InfoSec roles (e.g. penetration tester or open-source intelligence specialist) based on user preferences, so the users system is populated with relevant tools only.',
    'what_clearlinux'     : 'Clear Linux is a minimal distribution primarily designed with performance and cloud use-cases in mind. The operating system upgrades as a whole rather than using individual packages. Extra software can be added to the system (along with associated dependencies) using pre-compiled bundles which can be accessed through the distributions swupd software manager.',
    'what_centos'         : 'CentOS as a group is a community of open source contributors and users which started in 2003 and has been sponsored by Red Hat since 2014. CentOS Linux versions up to CentOS Linux 8 are 100% compatible rebuilds of Red Hat Enterprise Linux, in full compliance with Red Hats redistribution requirements. In 2020 it was announced CentOS Linux is being discontinued and replaced with CentOS Stream, a developer-focused distribution which acts as a middle-stream between Fedora and Red Hat Enterprise Linux.',
    'what_openmandriva_lx': 'The OpenMandriva distribution is a full-featured Linux desktop and server, sponsored by the OpenMandriva Association. It was based on ROSA, a Russian Linux distribution project which forked Mandriva Linux in 2012, incorporating many of Mandrivas original tools and utilities and adding in-house enhancements. The goal of OpenMandriva is to facilitate the creation, improvement, promotion and distribution of free and open-source software in general, and OpenMandriva projects in particular. OpenMandriva has traditionally been a fixed release distribution, but in 2023 the project began releasing an alternative rolling branch called ROME.',
    'what_fatdog64linux'  : 'Fatdog64 Linux is a small, desktop, 64-bit Linux distribution. Originally created as a derivative of Puppy Linux with additional applications, Fatdog64 has grown to become a distinct, separate project while maintaining much of the style of Puppy Linux.',
    'what_xubuntu'        : 'Xubuntu is a community-developed operating system based on Ubuntu. It comes with Xfce, which is a stable, light and configurable desktop environment.',
    'what_parrot'         : 'Parrot (formerly Parrot Security OS) is a Debian-based, security-oriented distribution featuring a collection of utilities designed for penetration testing, computer forensics, reverse engineering, hacking, privacy, anonymity and cryptography. The product, developed by Frozenbox, comes with MATE as the default desktop environment.',
    'what_neptune'        : 'Neptune is a GNU/Linux distribution for desktops. It is based on Debians Stable branch, except for a newer kernel, some drivers and newer versions of popular applications, such as LibreOffice. It also ships with the latest version of the KDE desktop. The distributions main goals are to provide a good-looking general-purpose desktop with pre-configured multimedia playback and to offer an easy-to-use USB installer with a persistence option.',
    'what_archcraft'      : 'Archcraft is a minimal Linux distribution based on Arch Linux. The project provides a graphical user interface using minimal window managers rather than full featured desktop environments. Archcraft is installed using the Calamares system installer and includes the yay package manager to facilitate fetching software from the Arch User Repository.',
    'what_linuxfx'        : 'Linuxfx is a Brazilian Linux distribution based on Ubuntu. It ships with an intuitive Cinnamon desktop user interface designed to facilitate migration of users from Windows. It includes a video management system called Sentinela, a computer vision software with video analytics and software for access control (facial recognition and automatic number plate recognition), object detection, gender, age and mood detection. Other features of the distribution include a new personal assistant, a WX theme for desktop and system applications, and compatibility with software written for Windows (.exe and .msi) through a Wine port. Following the release of Linuxfx 10.6 the distribution became a commercial offering.',
    'what_makululinux'    : 'MakuluLinux is a rolling-release, desktop distribution based either on Ubuntus LTS (long-term support) release or Debians "Testing" branch. It includes pre-installed multimedia codecs, device drivers and software for everyday use. MakuluLinux comes in four editions: "LinDoz" - featuring the Cinnamon desktop with the user interface customised to resemble that of Microsoft Windows, "Core" - presenting a highly customised Xfce desktop environment, "Flash" - providing a standard Xfce desktop, and finally "Shift" - delivering a pre-configured GNOME desktop environment.',
    'what_siduction'      : 'The siduction distribution is a desktop-oriented operating system and live medium based on the "unstable" branch of Debian GNU/Linux. Forked from aptosid in late 2011, siduction offers many separate live media with a range of desktop environments. The project also promises regular releases, an open development model, and friendly relationship with its developer and user community.',
    'what_qubesos'        : 'Qubes OS is a security-oriented, Fedora-based desktop Linux distribution whose main concept is "security by isolation" by using domains implemented as lightweight Xen virtual machines. It attempts to combine two contradictory goals: how to make the isolation between domains as strong as possible, mainly due to clever architecture that minimises the amount of trusted code, and how to make this isolation as seamless and easy as possible.',
    'what_artix' : 'Artix Linux is a fork (or continuation as an autonomous project) of the Arch-OpenRC and Manjaro-OpenRC projects. Artix Linux offers a lightweight, rolling-release operating system featuring the OpenRC init software. (Alternative spins feature the runit and s6 init software.) Several editions of Artix Linux are available, featuring either a plain command line or one of several desktop environments.',
    'what_steamos'        : 'SteamOS is a Debian-based Linux distribution designed to run Valves Steam and Steam games. It also provides a desktop mode (GNOME) which can run regular Linux applications. In addition to a stable Debian base, SteamOS features various third-party drivers and updated graphics stack, a newer Linux kernel with long-term support, and a custom graphics compositor designed to provide a seamless transition between Steam, its games and the SteamOS system overlay. The base operating system is open-source software, but the Steam client is proprietary.',
    'what_proxmox'        : 'Proxmox is a commercial company offering specialised products based on Debian GNU/Linux, notably Proxmox Virtual Environment and Proxmox Mail Gateway. Proxmox Virtual Environment is an open-source virtualisation platform for running virtual appliances and virtual machines. Proxmox Mail Gateway is a mail gateway with anti-spam and anti-virus features. The products are offered as free downloads with paid-for support and subscription options.',
    'what_biglinux'       : 'BigLinux is a Brazilian Linux distribution localised into Brazilian Portuguese (with support for English). It is was originally based on Kubuntu, but starting from 2017 the distribution was re-born based on deepin. It then offered two desktop environments - Cinnamon and Deepin. In 2021 the distribution switched bases and desktop environments again, migrating to Manjaro Linux running KDE Plasma.',
    'what_ultramarine'    : 'Ultramarine Linux is a Fedora-based distribution featuring extra package repositories such as RPM Fusion, the Budgie (or Cutefish) desktop, and multimedia codecs. Ultramarine can be considered a spiritual successor to Korora Project and aims to make Fedora a more desktop-friendly experience.',
    'what_absolutelinux'  : 'Absolute Linux is a light-weight modification of Slackware Linux. It includes several utilities that make configuration and maintenance easier and it has many common desktop and Internet applications installed and configured with tight integration of menus, applications and MIME types. Absolute Linux uses IceWM and ROX for its window and file managers.',
    'what_wattos'         : 'wattOS is a fast desktop Linux distribution based on Debian. Using the lightweight Openbox window manager as its default user interface, the distribution strives to be as energy-efficient as possible so that it can be used on low-specification and recycled computers.',
    'what_mabox'          : 'Mabox is a Manjaro-based rolling release distribution. Mabox Linux features the Openbox window manager as its default interface and provides a welcome screen with access to utilities which add additional software to the operating system.',
    'what_slax'           : 'Slax is a minimalist desktop live CD based on Slackware Linux. It boots into a simple desktop using the Fluxbox window manager which offers a small collection of applications, including the Chromium web browser, a text editor and a calculator. Prior to version 9.x, Slax was a Slackware-based live CD featuring the KDE desktop and a wide collection of pre-installed software for daily use together with useful recovery tools for system administrators. After releasing version 11.x with a Debian base, the project returned to a Slackware base for version 15.0.0.',
    'what_ubuntumate'     : 'Ubuntu MATE is a desktop Linux distribution which aims to bring the simplicity and elegance of the Ubuntu operating system through a classic, traditional desktop environment - the MATE desktop. MATE is the continuation of the GNOME 2 desktop environment which was used as Ubuntus default desktop until 10.10 (when it was replaced by Unity). The project began its life as an Ubuntu remix, but starting with version 15.04, it was formally accepted as an official member of the Ubuntu family of Linux distributions.',
    'what_4mlinux'        : '4MLinux is a miniature Linux distribution focusing on four capabilities: maintenance (as a system rescue live CD), multimedia (for playing video DVDs and other multimedia files), miniserver (using the inetd daemon), and mystery (providing several small Linux games). The distribution includes support for booting on UEFI-enabled machines.',
    'what_lxle'           : 'LXLE is an easy-to-use lightweight desktop Linux distribution based on Lubuntu and featuring the LXDE desktop environment. Compared to its parent, LXLE has a number of unique characteristics: it is built from Ubuntus LTS (long-term support) releases, it covers most users everyday needs by providing a good selection of default applications, and it adds useful modifications and tweaks to improve performance and functions.',
    'what_bros'           : 'Br OS is a Brazilian Linux distribution based on Ubuntu and featuring the KDE Plasma desktop. It is designed as an intuitive, easy-to-use, general-purpose operating system for web navigation and content creation, providing a selection of useful applications for daily use.',
    'what_ferenos'        : 'Feren OS is a desktop Linux distribution based on Ubuntu and featuring the KDE Plasma desktop. It ships with a tweaked Calamares system installer, a custom theme and fonts, the Vivaldi web browser, boot options for advanced users, and a Feren OS Tour application, among the many home-built features and improvements. Prior to November 2020, the distribution was based on Linux Mint and included an edition with the Cinnamon desktop.',
    'what_ubuntustudio'   : 'An official variant of Ubuntu, Ubuntu Studio is a Linux-based operating system for creative individuals in the areas of audio production, video production, graphics design, photography and desktop publishing. It makes professional audio accessible on Linux; it uses the JACK sound server and a kernel built with a low-latency patch. Up until version 20.10 Ubuntu Studio shipped with the Xfce desktop environment, but this was replaced by KDE Plasma in October 2020.',
    'what_nutyx'          : 'NuTyX is a French Linux distribution (with multi-language support) built from Linux From Scratch and Beyond Linux From Scratch, with a custom package manager called "cards". The package manager can install individual binary packages, a group of related binary packages (e.g. desktop packages, such as KDE or Xfce), and compile source packages from "ports". The distribution is designed for intermediate and advanced Linux users.',
    'what_linuxkodachi'   : 'Linux Kodachi is a Debian-based distribution which can be run from a DVD or USB thumb drive. The distribution filters all network traffic through a VPN and the Tor network, obscuring the users network location. The distribution attempts to clean up after itself, removing traces of its use from the computer.',
    'what_archman'        : 'Archman GNU/Linux is an Arch Linux-based distribution which features the Calamares system installer and a pre-configured desktop environment. Archman also features the Pamac package manager for easy installation of new software packages.',
    'what_deepin'         : 'deepin (formerly, Deepin, Linux Deepin, Hiweed GNU/Linux) is a Debian-based distribution (it was Ubuntu-based until version 15 released in late 2015) that aims to provide an elegant, user-friendly and reliable operating system. It does not only include the best the open source world has to offer, but it has also created its own desktop environment called DDE or Deepin Desktop Environment which is based on the Qt 5 toolkit. Deepin focuses much of its attention on intuitive design. Its home-grown applications, like Deepin Software Centre, DMusic and DPlayer are tailored to the average user. Being easy to install and use, deepin can be a good Windows alternative for office and home use.',
    'what_geckolinux'     : 'GeckoLinux is a Linux spin based on the openSUSE distribution, with a focus on polish and out-of-the-box usability on the desktop. The distribution features many desktop editions which can be installed from live discs. Some patent encumbered open source software is included in GeckoLinux which is not available in the default installation of openSUSE. Special attention has been given to the quality of the font rendering. GeckoLinux provides two main editions, Static (which is based on openSUSE Leap) and Rolling (based on openSUSE Tumbleweed).',
    'what_nitrux'         : 'Nitrux is a Linux distribution based on Debians Unstable (sid) branch with additional packages pulled in from Ubuntu LTS repositories. Nitrux strives to be a distribution suitable for laptops and desktop computers. Its main desktop environment is NX Desktop, a KDE Plasma desktop enhanced with plasmoids to create a special blend of aesthetics and functionality. The project also focuses on using redistributable, portable applications using the AppImage format. Registration with an e-mail address was required to download this distribution, however public downloads have been available since mid-2020.',
    'what_blackarch'      : 'BlackArch Linux is an Arch Linux-based distribution designed for penetration testers and security researchers. It is supplied as a live DVD image that comes with several lightweight window managers, including Fluxbox, Openbox, Awesome and spectrwm. It ships with over a thousand specialist tools for penetration testing and forensic analysis.',
    'what_blackarchlinux' : 'BlackArch Linux is an Arch Linux-based distribution designed for penetration testers and security researchers. It is supplied as a live DVD image that comes with several lightweight window managers, including Fluxbox, Openbox, Awesome and spectrwm. It ships with over a thousand specialist tools for penetration testing and forensic analysis.',
    'what_debain'         : 'The Debian Project is an association of individuals who have made common cause to create a free operating system. This operating system is called Debian. Debian systems currently use the Linux kernel. Linux is a completely free piece of software started by Linus Torvalds and supported by thousands of programmers worldwide. Of course, the thing that people want is application software: programs to help them get what they want to do done, from editing documents to running a business to playing games to writing more software. Debian comes with over 50,000 packages (precompiled software that is bundled up in a nice format for easy installation on your machine) - all of it free. Its a bit like a tower. At the base is the kernel. On top of that are all the basic tools. Next is all the software that you run on the computer. At the top of the tower is Debian -- carefully organizing and fitting everything so it all works together.',
}

question = input('What Do You Want To Know? Enter in the Syntax Here (Do "help_syntax" for the Syntax) -->')
print(data_lib[question])

while True:
    question = input('What Do You Want To Know? Enter in the Syntax Here (Do "help_syntax" for the Syntax) -->')
    print(data_lib[question])
